services:
  postgres:
    image: postgres
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT}:5432"
volumes:
  postgres_data:
    name: postgres_data
